name: deplpoy
on:
  push:

permissions:
  contents: read
  pages: write
  id-token: write
  packages: write

jobs:
  build:
    name: Build and export
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Cache node modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          # npm キャッシュファイルは Linux/macOS の「~/.npm」に保存される
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-

      - name: Install modules
        run: npm ci

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get devcontainer for ogimage
        run: npm run ogimage:devcontainer

      - name: Generate ogimages inside Dev Container
        uses: devcontainers/ci@v0.2
        with:
          imageName: ghcr.io/hankei6km/test-marp-ogimage-pages
          cacheFrom: ghcr.io/hankei6km/test-marp-ogimage-pages
          push: always
          subFolder: .devcontainer/ogimage
          runCmd: |
            npm run ogimage

      - name: Export
        run: npm run export

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./out

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
